spring.application.name=gecm-lostfound

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/gecm_lostfound_v2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.thymeleaf.cache=false

app.upload.dir=uploads
